# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: lint
      - task: test
      - task: build
  build:
    cmds:
      - go build -ldflags "-X main.commit=$(git rev-parse HEAD) -X main.date=$(date --iso-8601)" -o gh-action-escape ./cmd/gh-action-escape
  test:
    cmds:
      - go test ./...
  fmt:
    cmds:
      - typos . .github .vscode --write-changes
      - dprint fmt
      - go fmt ./...
      - nixpkgs-fmt ./*.nix
  lint:
    # go fmt does not have option for no effect - https://github.com/golang/go/issues/41189
    cmds:
      - dprint check
      - go vet ./...
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
  deps:
    cmds:
      - nix --version
      - task --version
      - go version
      - dprint --version
      - typos --version
