# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: lint
      - task: test
      - task: build
  install:
    cmds:
      - go install -ldflags "-X main.commit=$(git rev-parse HEAD) -X main.date=$(date --iso-8601)"
  build:preview:
    cmds:
      - goreleaser build --snapshot --single-target --clean --output dist/gh-action-escape
  build:
    cmds:
      - go build -o ./dist/bin/gh-action-escape ./cmd/gh-action-escape
  test:
    cmds:
      - go test ./...
  fmt:
    cmds:
      - typos . .github .vscode --write-changes
      - dprint fmt
      - go fmt ./...
      - nixfmt ./*.nix
  lint:
    # go fmt does not have option for no effect - https://github.com/golang/go/issues/41189
    cmds:
      - dprint check
      - go vet ./...
      - goreleaser check
      - typos . .github .vscode
      - nixfmt --check ./*.nix
      - git ls-files | xargs selfup list -check
  selfup:
    cmds:
      - git ls-files | xargs selfup run
  deps:
    cmds:
      - nix --version
      - task --version
      - go version
      - dprint --version
      - typos --version
      - goreleaser --version
      - nixfmt --version
