# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: lint
      - task: test
      - task: build
  install:
    cmds:
      - go install -ldflags "-X main.commit=$(git rev-parse HEAD) -X main.date=$(date --iso-8601)"
  build:preview:
    cmds:
      - goreleaser build --snapshot --single-target --clean --output dist/gh-action-multiline
  build:
    cmds:
      - go build -o ./dist/bin/gh-action-multiline ./cmd/gh-action-multiline
  test:
    cmds:
      - go test
  fmt:
    cmds:
      - dprint fmt
      - go fmt
      - nixpkgs-fmt ./*.nix
  lint:
    # go fmt does not have option for no effect - https://github.com/golang/go/issues/41189
    cmds:
      - dprint check
      - go vet
      - goreleaser check
      - nixpkgs-fmt --check ./*.nix
  deps:
    cmds:
      - nix --version
      - task --version
      - go version
      - dprint --version
      - goreleaser --version
