name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        # Keep same version as used in *.nix
        # https://github.com/rhysd/actionlint/blob/590d3bd9dde0c91f7a66071d40eb84716526e5a6/scripts/download-actionlint.bash#L46-L47
        # https://stackoverflow.com/questions/4642915/passing-parameters-to-bash-when-executing-a-script-fetched-by-curl
        run: curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- 1.6.24
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
