name: CI - E2E
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-e2e.yml'
      - 'scripts/**'
      - 'examples/**'
  pull_request:
    paths:
      - '.github/workflows/ci-e2e.yml'
      - 'scripts/**'
      - 'examples/**'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  usage:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install gh-action-escape
        run: curl -fsSL https://raw.githubusercontent.com/kachick/gh-action-escape/${{ github.sha }}/scripts/install-in-github-action.sh | sh -s v0.2.0
      - name: Set the value in bash
        id: step_output
        run: cat examples/example.json | gh-action-escape -name=example_json >> "$GITHUB_OUTPUT"
      - name: Use product in a before step
        run: test '6174' = "${{ fromJson(steps.step_output.outputs.example_json).nested.kaprekar_constant }}"
      - name: Set the value in bash
        id: step_env
        run: cat examples/example.json | gh-action-escape -name=EXAMPLE_JSON >> "$GITHUB_ENV"
      - name: Use product in a before step
        run: test '42' = "${{ fromJson(env.EXAMPLE_JSON).the_answer }}"
