name: CI - Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '*.nix'
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.nix'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - run: go test ./...
      - run: go build -v -race ./...
  usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
      - run: task build
      - run: tree dist
      - run: readlink -f ./dist/bin >> "$GITHUB_PATH"
      - run: gh-action-escape -name=example_json < examples/example.json | tee -a "$GITHUB_OUTPUT"
        id: have_output
      - run: test '6174' = "${{ fromJson(steps.have_output.outputs.example_json).nested.kaprekar_constant }}"
      - name: Output multiple key-value pairs in a step
        run: |
          gh-action-escape -name=example_json < examples/example.json | tee -a "$GITHUB_OUTPUT"
          gh-action-escape -name=strange_text < examples/strange.txt | tee -a "$GITHUB_OUTPUT"
        id: have_multiple_outputs
      - name: Test above
        run: |
          test '42' = "${{ fromJson(steps.have_multiple_outputs.outputs.example_json).the_answer }}"
          test "looks_like_a_name=and_looks_like_the_value" = "${{ steps.have_multiple_outputs.outputs.strange_text }}"
      - uses: actions/upload-artifact@v4
        with:
          name: gh-action-escape
          path: dist/bin/gh-action-escape
          if-no-files-found: error
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: lint
        run: go vet ./...
      - name: format
        run: go fmt ./... && git add --intent-to-add . && git diff --exit-code
