name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '*.nix'
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.nix'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - run: go test
      - run: go build -v -race
  usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - run: task build
      - run: tree dist
      - run: readlink -f ./dist/gh-action-multiline_linux_amd64_v1 >> "$GITHUB_PATH"
      - run: gh-action-multiline -name=example_json < examples/example.json | tee -a "$GITHUB_OUTPUT"
        id: have_output
      - run: test '6174' = "${{ fromJson(steps.have_output.outputs.example_json).nested.kaprekar_constant }}"
      - uses: actions/upload-artifact@v3
        with:
          name: gh-action-multiline
          path: dist/gh-action-multiline_linux_amd64_v1/gh-action-multiline
          if-no-files-found: error
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: lint
        run: go vet
      - name: format
        run: go fmt && git add --intent-to-add . && git diff --exit-code
