name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  checks: read # For private repositories
  actions: read # For private repositories

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cli/gh-extension-precompile@v1
        with:
          # TODO: Use `go.mod` if https://github.com/cli/gh-extension-precompile/issues/46 available
          go_version: '1.21'
