name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read # For private repositories
  actions: read # For private repositories

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      # TODO: Enable after https://github.com/kachick/wait-other-jobs/issues/474
      # - name: Wait other jobs
      #   uses: kachick/wait-other-jobs@v1.3.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: 'v1.19.2' # selfup { "regex": "\\d[^']+", "script": "goreleaser --version | grep 'GitVersion:' | tr -s ' ' | cut -d ' ' -f 2" }
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
